[package]
name = "reqwest-pipeline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
chrono = "^0.4"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
log = "0.4.11"
url = "^2.2"
http = "0.2"
bytes = "1"
async-trait = "0.1"
dyn-clone = "1"
futures = "0.3"
rand = "*"
reqwest = { version = "0.11", features = ["stream"], default_features = false }
base64 = { version = "*", optional = true }

[dev-dependencies]
env_logger = "0.9"
tokio = { version = "1", features = ["default"] }

[features]
mock_transport_framework = ["base64"]
