version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - Introspector
  - chrono
  - datafusion
  - datasource
  - dotenv
  - prost
  - proto
  - protobuf
  - unpartitioned
import: []
