version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - Datetime
  - Hasher
  - Introspector
  - Kubernetes
  - Kusto
  - Pageable
  - Popen
  - Timespan
  - addinivalue
  - betterproto
  - chrono
  - clippy
  - codegen
  - dagit
  - datafusion
  - datalake
  - datasource
  - deps
  - dotenv
  - filetime
  - hmac
  - httpx
  - isort
  - itertools
  - jdbc
  - maturin
  - mkdocs
  - mlflow
  - mlserver
  - opentelemetry
  - petgraph
  - plotly
  - prost
  - proto
  - protobuf
  - pyclass
  - pydantic
  - pyfunction
  - pymethods
  - pymodule
  - pyright
  - quicktype
  - reqwest
  - ritelinked
  - rustfmt
  - schemafy
  - seekable
  - sklearn
  - sqlparser
  - structopt
  - tempdir
  - tempfile
  - toposort
  - typer
  - unpartitioned
  - virtualenvs
  - walkdir
import: []
