version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - Datetime
  - Introspector
  - Kusto
  - Pageable
  - Timespan
  - chrono
  - clippy
  - datafusion
  - datasource
  - deps
  - dotenv
  - hmac
  - jdbc
  - mkdocs
  - opentelemetry
  - petgraph
  - prost
  - proto
  - protobuf
  - pyclass
  - pyfunction
  - pymethods
  - pymodule
  - quicktype
  - reqwest
  - rustfmt
  - schemafy
  - seekable
  - sqlparser
  - structopt
  - tempfile
  - toposort
  - unpartitioned
import: []
