version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - Introspector
  - Kusto
  - Pageable
  - chrono
  - clippy
  - datafusion
  - datasource
  - dotenv
  - prost
  - proto
  - protobuf
  - quicktype
  - reqwest
  - rustfmt
  - schemafy
  - seekable
  - structopt
  - tempfile
  - unpartitioned
import: []
