version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - Datetime
  - Introspector
  - Kubernetes
  - Kusto
  - Pageable
  - Timespan
  - chrono
  - clippy
  - codegen
  - datafusion
  - datalake
  - datasource
  - deps
  - dotenv
  - hmac
  - itertools
  - jdbc
  - mkdocs
  - opentelemetry
  - petgraph
  - prost
  - proto
  - protobuf
  - pyclass
  - pydantic
  - pyfunction
  - pymethods
  - pymodule
  - quicktype
  - reqwest
  - rustfmt
  - schemafy
  - seekable
  - sqlparser
  - structopt
  - tempdir
  - tempfile
  - toposort
  - unpartitioned
  - walkdir
import: []
