[server]
port = "50051"
url = "0.0.0.0"
service_name = "flight-fusion"

[service]
storage = "file"

[service.local]
area_root = "./.flight-fusion/.fusion"
artifacts_root = "./.flight-fusion/.mlflow/mlruns"

[service.azure]
account = ""
key = ""
file_system = ""

[service.cache]
root = "./_ff_cache"
max_size_mb = 100

[log]
level = "info"
